#! /usr/bin/env python
# Extracts Siemens' realignment parameters from a MoCo EPI scan series 
# Time-stamp: <2012-03-14 11:45 christophe@pallier.org>

"""
Given a directory or a tar file containing scans in the mosaic dicom format,
print the 'MoCo*' fields (Motion Correction, generated by some Siemens sequences)
"""

import dicom
import os, sys, fnmatch

import tarfile, tempfile

def locate(pattern, root=os.curdir):
    for path, dirs, files in os.walk(os.path.abspath(root)):
        for filename in fnmatch.filter(files, pattern):
            yield os.path.join(path, filename)

if __name__ == '__main__':
    tname = sys.argv[1]
    if os.path.isdir(tname):
        tempdir = tname
        existdir = 1
    else:
        existdir = 0
        if tarfile.is_tarfile(tname):
            tempdir = tempfile.mkdtemp()
            tar = tarfile.open(tname)
            tar.extractall(path=tempdir)
        else:
            print('The first argument must be either a directory or a tar file')
            exit(1)

    for files in locate('*.MRDC', root=tempdir):
            plan = dicom.read_file(files)
            MoCoTrans = plan[0x0019,0x1025].value
            MoCoRot = plan[0x0019,0x1026].value
            print MoCoTrans[0],MoCoTrans[1],MoCoTrans[2], MoCoRot[0], MoCoRot[1], MoCoRot[2]
            
            # SequenceName = plan.SequenceName
            # RepetitionTime = plan.RepetitionTime
            # EchoTime = plan.EchoTime
            # FlipAngle = plan.FlipAngle
            # SliceThickness = plan.SliceThickness
            # SpacingBetweenSlices = plan.SpacingBetweenSlices

    if existdir == 0:
        tar.close()


        
